### ISSUE TITLE
Integrate Hackathon Changes to odevs-website

### ISSUE THREAD

**Issue by robschn** [OrlandoDevs/website#4]
During our last hackathon, some great and critical changes were made in order to improve the existing website. The changes should be integrated and deployed in order to give us a good foundation for new updates and feature enhancements before our code freeze October 31st, 2024

**Comment by wgeorgecook** [comment]
The hackathon changes were merged in by @snohio in https://github.com/OrlandoDevs/odevs-web/pull/63
